### ISSUE TITLE
Error while creating change log 

### ISSUE THREAD

**Issue by Dhruva23** [tomasbjerre/git-changelog-lib#107]
Getting below error 

se.bjurr.gitchangelog.api.exceptions.GitChangelogRepositoryException .md file not found in jenkins workspace.

Git change log plugin version : 3.13

at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1160)
		at org.jenkinsci.plugins.gitchangelog.steps.GitChangelogStep$1.run(GitChangelogStep.java:338)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)

Jenkins version : 2.250

**Comment by tomasbjerre** [comment]
Are you sure there is not more stacktrace?
How did you configure the plugin?

**Comment by Dhruva23** [comment]
Hi,

I have configured using Jenkins, manage plugins,

**Comment by Dhruva23** [comment]
Even changeling.md is created in local work space

**Comment by tomasbjerre** [comment]
Can you supply your pipeline code?

**Comment by Dhruva23** [comment]
def changelogString = gitChangelog returnType: 'STRING',
  from: [type: 'REF', value: 'CHANGELOG.md'],
  to: [type: 'REF', value: 'demo'],

**Comment by tomasbjerre** [comment]
ref should be a branch or a tag. You probably dont have such a branch or tag named `CHANGELOG.md`.

**Comment by Dhruva23** [comment]
def changelogString = gitChangelog returnType: 'STRING',
  from: [type: 'REF', value: 'CHANGELOG.md'],
  to: [type: 'REF', value: 'demo'],
  template: """
  <h1> Git Changelog changelog </h1>

<p>
Changelog of Git Changelog.
</p>

{{#tags}}
<h2> {{name}} </h2>
 {{#issues}}
  {{#hasIssue}}
   {{#hasLink}}
<h2> {{name}} <a href="{{link}}">{{issue}}</a> {{title}} </h2>
   {{/hasLink}}
   {{^hasLink}}
<h2> {{name}} {{issue}} {{title}} </h2>
   {{/hasLink}}
  {{/hasIssue}}
  {{^hasIssue}}
<h2> {{name}} </h2>
  {{/hasIssue}}


   {{#commits}}
<a href="https://github.com/tomasbjerre/git-changelog-lib/commit/{{hash}}">{{hash}}</a> {{authorName}} <i>{{commitTime}}</i>
<p>
<h3>{{{messageTitle}}}</h3>

{{#messageBodyItems}}
 <li> {{.}}</li> 
{{/messageBodyItems}}
</p>


  {{/commits}}

 {{/issues}}
{{/tags}}
  """

**Comment by Dhruva23** [comment]
at se.bjurr.gitchangelog.internal.git.GitRepo.getRef(GitRepo.java:139)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getId(GitChangelogApi.java:615)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:567)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:83)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:109)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:140)
	at org.jenkinsci.plugins.gitchangelog.steps.GitChangelogStep.perform(GitChangelogStep.java:422)
	at org.jenkinsci.plugins.gitchangelog.steps.GitChangelogStep.access$000(GitChangelogStep.java:45)
	at org.jenkinsci.plugins.gitchangelog.steps.GitChangelogStep$1$1.call(GitChangelogStep.java:334)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Dhruva23** [comment]
> ref should be a branch or a tag. You probably dont have such a branch or tag named `CHANGELOG.md`.
Given some this like this
def changelogString = gitChangelog returnType: 'STRING',
  from: [type: 'REF', value: 'demo'],
  to: [type: 'REF', value: 'demo'],
thought build is successful, in workspace not able to find demo

**Comment by Dhruva23** [comment]
am I missing some thing

**Comment by Dhruva23** [comment]
managed to resolve issue, gitChangelog from: [type: 'REF', value: 'demo'], returnType: 'STRING', to: [type: 'REF', value: 'demo']
how to save it to changelog.md file, in free style job we can.
