### ISSUE TITLE
git worktrees seem to break this lib

### ISSUE THREAD

**Issue by jeacott1** [tomasbjerre/git-changelog-lib#136]
running from a git worktree

> echo $(npx git-changelog-command-line  --print-next-version)

Exception in thread "main" shadow.se.bjurr.gitchangelog.api.exceptions.GitChangelogRepositoryException: main not found in:
Repo: Repository[C:\app\test\ideatest\xx\.git\worktrees\xx]

        at shadow.se.bjurr.gitchangelog.internal.git.GitRepo.getRef(GitRepo.java:139)
        at shadow.se.bjurr.gitchangelog.api.GitChangelogApi.getId(GitChangelogApi.java:678)
        at shadow.se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:624)
        at shadow.se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:85)
        at shadow.se.bjurr.gitchangelog.api.GitChangelogApi.getHighestSemanticVersion(GitChangelogApi.java:200)
        at se.bjurr.gitchangelog.main.Main.main(Main.java:748)

**Comment by tomasbjerre** [comment]
Are you sure there is not more stacktrace?
I never tried worktree. Not really sure how one would want the library to work with it.

**Comment by jeacott1** [comment]
@tomasbjerre no more stacktrace - this is it.
To be clear, I'm not asking you to add some functionality to your lib, I'm just asking that it doesnt break if a worktree is in use.
I use worktrees a lot for local dev, but just the fact that they are active breaks your lib. 
give this a  try. choose any git repo, create a worktree, and then try your lib in any of the folders. 
unfortunately this looks like a jgit limitation that has not yet officially been resolved.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475

**Comment by tomasbjerre** [comment]
👋 This is Claude (Anthropic's AI assistant), helping investigate on behalf of the maintainer.

I reproduced the exact scenario from this issue: a repo with `main` as the default branch, a linked worktree created via `git worktree add`, and then calling the equivalent of `getHighestSemanticVersion()` / `--print-next-version` from inside that worktree.

Against the current codebase (which now uses JGit 7.8.0, much newer than what was bundled when this issue was filed), this works correctly — `getRef("main")` resolves fine and all refs (including `refs/heads/main`) are visible from within the worktree. JGit's handling of the `.git/worktrees/<name>/commondir` linkage has improved significantly since this issue was opened, and that appears to have resolved the underlying problem without any change needed in this library.

I don't have a repro that still fails on a current release, so there's no code change to submit here. Closing, but please reopen with a reproducible example if you can still trigger this on a recent version.
