### ISSUE TITLE
Did not find a GIT repo

### ISSUE THREAD

**Issue by serhiylehkodukh** [tomasbjerre/git-changelog-lib#32]
Hello. Have some problem with changelog plugin. I have 5 repos in that path, plugin didn't find them
--- Git Changelog ---

gitchangelog.api.exceptions.GitChangelogRepositoryException: Did not find a GIT repo in C:\Program Files (x86)\Jenkins\jobs\qwerty\workspace\Dependencies
	at se.bjurr.gitchangelog.internal.git.GitRepo.<init>(GitRepo.java:69)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:73)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:97)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:130)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.FilePath.act(FilePath.java:1105)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:29)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:52)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

**Comment by tomasbjerre** [comment]
Is there a `.git` folder in `C:\Program Files (x86)\Jenkins\jobs\qwerty\workspace\Dependencies`?

If there are 5 repos in different subfolders, you must choose one. You can use the checkbox "Use a subdirectory relative to the workspace".

**Comment by tomasbjerre** [comment]
no response, closing

**Comment by kenandroid** [comment]
I have the same issue but I am using the pipeline.  How would I set a subfolder using pipeline?  I have tried fromRepo: Android (Android is the name of my subfolder)  I also tried sh "cd ./Android" as I see in your code if fromRepo is null you pull the current directory but that doesn't seem to work either.

**Comment by tomasbjerre** [comment]
I guess you are using this Jenkins Plugin? https://github.com/jenkinsci/git-changelog-plugin
And if so, you can set `subDirectory` like this:
```
...
useSubDirectory(true)
subDirectory("Android")
...
```
There is no option named `fromRepo`.

**Comment by kenandroid** [comment]
That worked, is there a doc for all properties I can use in a pipeline?  I am also trying to get specific commit points by commit hash but the 2 options I tried did not seem to work.

fromReference
fromCommit

**Comment by tomasbjerre** [comment]
There is just the [Snipped Generator](https://jenkins.io/doc/book/pipeline/getting-started/#snippet-generator).

**Comment by kenandroid** [comment]
The only issue with that is I don't see ChangeLog in my list of steps.  I have restarted my jenkins instance after installing the plugin but it still doesn't appear.

**Comment by tomasbjerre** [comment]
It is here:
![snippet-generator](https://user-images.githubusercontent.com/439571/34741224-33d135d2-f582-11e7-8426-f7bc704df955.png)

**Comment by kenandroid** [comment]
Using that I get an error creating the file.  I chmod 777 the parent folder to make sure no permission issues should exist.  I used the default file name.

Creating changelog CHANGELOG.htmljava.io.IOException: Could not make dirs /Users/Shared/Jenkins/Home/workspace/MBX_Android_CI-Sandbox
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:190)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.FilePath.act(FilePath.java:1083)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:40)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:52)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:78)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:65)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tomasbjerre** [comment]
That is actually a bug. Fixing it here: https://github.com/jenkinsci/git-changelog-plugin/commit/1a46e41f521dbc3cea19e787a21e7ab51518e1cd

Releasing 1.57 now with that fix. Should be available in update site within a few hours.

**Comment by kenandroid** [comment]
I now get the following.  I will include my pipeline script as well.  For the most part it is the default.

Creating changelog CHANGELOG.htmljava.lang.RuntimeException: Cannot find on classpath (changelog.mustache) or filesystem (/Users/Shared/Jenkins/changelog.mustache).
	at se.bjurr.gitchangelog.api.GitChangelogApi.getTemplateContent(GitChangelogApi.java:502)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:94)
	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:123)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:189)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.FilePath.act(FilePath.java:1083)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:40)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:52)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:78)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:65)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: changelog.mustache (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.google.common.io.Files$1.getInput(Files.java:105)
	at com.google.common.io.Files$1.getInput(Files.java:102)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:249)
	at com.google.common.io.Files.toByteArray(Files.java:197)
	at com.google.common.io.Files.toString(Files.java:223)
	at se.bjurr.gitchangelog.api.GitChangelogApi.getTemplateContent(GitChangelogApi.java:496)




step([$class: 'GitChangelogRecorder', config: [configFile: 'git-changelog-settings.json', createFileTemplateContent: '''<h1> Git Changelog changelog </h1>

<p>
Changelog of Git Changelog.
</p>

{{#tags}}
<h2> {{name}} </h2>
 {{#issues}}
  {{#hasIssue}}
   {{#hasLink}}
<h2> {{name}} <a href="{{link}}">{{issue}}</a> {{title}} </h2>
   {{/hasLink}}
   {{^hasLink}}
<h2> {{name}} {{issue}} {{title}} </h2>
   {{/hasLink}}
  {{/hasIssue}}
  {{^hasIssue}}
<h2> {{name}} </h2>
  {{/hasIssue}}


   {{#commits}}
<a href="https://github.com/tomasbjerre/git-changelog-lib/commit/{{hash}}">{{hash}}</a> {{authorName}} <i>{{commitTime}}</i>
<p>
<h3>{{{messageTitle}}}</h3>

{{#messageBodyItems}}
 <li> {{.}}</li> 
{{/messageBodyItems}}
</p>
  {{/commits}}

 {{/issues}}
{{/tags}}
''', createFileTemplateFile: '', customIssues: [[link: '', name: '', pattern: '', title: ''], [link: '', name: '', pattern: '', title: '']], dateFormat: 'YYYY-MM-dd HH:mm:ss', file: 'CHANGELOG.html', fromReference: 'e7dc47f75333fa6788cb8d13adbba70cce008497', fromType: 'commit', gitHubApi: '', gitHubApiTokenCredentialsId: '', gitHubIssuePattern: '#([0-9]+)', gitHubToken: '', gitLabApiTokenCredentialsId: '', gitLabProjectName: '', gitLabServer: '', gitLabToken: '', ignoreCommitsIfMessageMatches: '^\\[maven-release-plugin\\].*|^\\[Gradle Release Plugin\\].*|^Merge.*', ignoreTagsIfNameMatches: '', jiraIssuePattern: '\\b[a-zA-Z]([a-zA-Z]+)-([0-9]+)\\b', jiraPassword: '', jiraServer: '', jiraUsername: '', jiraUsernamePasswordCredentialsId: '', mediaWikiPassword: '', mediaWikiTemplateContent: '''__NOTOC__

= Git Changelog changelog =
Changelog of Git Changelog.

{{#tags}}
== {{name}} ==
 {{#issues}}
  {{#hasIssue}}
   {{#hasLink}}
=== {{name}} [{{link}} {{issue}}] {{title}} ===
   {{/hasLink}}
   {{^hasLink}}
=== {{name}} {{issue}} {{title}} ===
   {{/hasLink}}
  {{/hasIssue}}
  {{^hasIssue}}
=== {{name}} ===
  {{/hasIssue}}

   {{#commits}}
[https://github.com/tomasbjerre/git-changelog-lib/commit/{{hash}} {{hash}}] {{authorName}} {{commitTime}}

\'\'\'{{{messageTitle}}}\'\'\'

{{#messageBodyItems}}
 * {{.}} 
{{/messageBodyItems}}

  {{/commits}}

 {{/issues}}
{{/tags}}
''', mediaWikiTemplateFile: '', mediaWikiTitle: '', mediaWikiUrl: '', mediaWikiUsername: '', noIssueName: 'No issue', readableTagName: '/([^/]+?)$', showSummaryTemplateContent: '''<h1> Git Changelog changelog </h1>

<p>
Changelog of Git Changelog.
</p>

{{#tags}}
<h2> {{name}} </h2>
 {{#issues}}
  {{#hasIssue}}
   {{#hasLink}}
<h2> {{name}} <a href="{{link}}">{{issue}}</a> {{title}} </h2>
   {{/hasLink}}
   {{^hasLink}}
<h2> {{name}} {{issue}} {{title}} </h2>
   {{/hasLink}}
  {{/hasIssue}}
  {{^hasIssue}}
<h2> {{name}} </h2>
  {{/hasIssue}}


   {{#commits}}
<a href="https://github.com/tomasbjerre/git-changelog-lib/commit/{{hash}}">{{hash}}</a> {{authorName}} <i>{{commitTime}}</i>
<p>
<h3>{{{messageTitle}}}</h3>

{{#messageBodyItems}}
 <li> {{.}}</li> 
{{/messageBodyItems}}
</p>


  {{/commits}}

 {{/issues}}
{{/tags}}
''', showSummaryTemplateFile: '', subDirectory: 'Android', timeZone: 'UTC', toReference: '5f881607a03fb96394dbac584cfa0cd77ecf187b', toType: 'commit', untaggedName: 'Unreleased', useFile: true, useSubDirectory: true]])

**Comment by tomasbjerre** [comment]
Probably fixed by adding `createFileUseTemplateContent: true`. It should have been added if you used the snippet gernerator.
