### ISSUE TITLE
Error while trying to create the changelog file.

### ISSUE THREAD

**Issue by GangaramD** [tomasbjerre/git-changelog-lib#51]
ERROR: Step ‘Git Changelog’ aborted due to exception: 
java.lang.NoClassDefFoundError: Could not initialize class se.bjurr.gitchangelog.internal.settings.Settings
	at se.bjurr.gitchangelog.api.GitChangelogApi.<init>(GitChangelogApi.java:430)
	at se.bjurr.gitchangelog.api.GitChangelogApi.gitChangelogApiBuilder(GitChangelogApi.java:57)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:56)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.FilePath.act(FilePath.java:1083)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:40)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:52)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE

**Comment by tomasbjerre** [comment]
What version of Jenkins? And what version of the plugin?

**Comment by GangaramD** [comment]
Jenkins 2.46.1 and plugin-1.51

**Comment by GangaramD** [comment]
Posting changelog to http://localhost/mediawiki/index.php/Devse.bjurr.gitchangelog.api.exceptions.GitChangelogIntegrationException: http://localhost/mediawiki Dev
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.createMediaWikiPage(MediaWikiClient.java:95)
	at se.bjurr.gitchangelog.api.GitChangelogApi.toMediaWiki(GitChangelogApi.java:134)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:167)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.FilePath.act(FilePath.java:1085)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:40)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:52)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:730)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Caused by: com.jayway.jsonpath.PathNotFoundException: Missing property in path $['login']
	at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:72)
	at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:77)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:147)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:502)
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.getWikiToken(MediaWikiClient.java:192)
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.doAuthenticate(MediaWikiClient.java:177)
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.createMediaWikiPage(MediaWikiClient.java:86)
	... 16 more

**Comment by tomasbjerre** [comment]
Are you intending to create a mediawiki page?

**Comment by GangaramD** [comment]
Yes

**Comment by tomasbjerre** [comment]
Did you supply username/password ? How did you configure the plugin? Can you supply a screenshot? Or pipeline?

**Comment by GangaramD** [comment]
![image](https://user-images.githubusercontent.com/22867715/29377778-81da455e-82da-11e7-94a3-a4f053745f8b.png)

**Comment by tomasbjerre** [comment]
Did you enable the API in mediawiki?

```
The library can create a wiki page in MediaWiki. To do this, you must enable the API in MediaWiki in mediawiki/LocalSettings.php by adding:

$wgEnableAPI = true;
$wgEnableWriteAPI = true;
```

**Comment by GangaramD** [comment]
now again i am getting this issue,

ERROR: Step ‘Git Changelog’ aborted due to exception: 
java.lang.ClassNotFoundException: com.google.gson.Gson
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
Caused: java.lang.NoClassDefFoundError: com/google/gson/Gson
	at se.bjurr.gitchangelog.internal.settings.Settings.<clinit>(Settings.java:34)
	at se.bjurr.gitchangelog.api.GitChangelogApi.<init>(GitChangelogApi.java:430)
	at se.bjurr.gitchangelog.api.GitChangelogApi.gitChangelogApiBuilder(GitChangelogApi.java:57)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:56)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.FilePath.act(FilePath.java:1083)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:40)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:52)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE

**Comment by GangaramD** [comment]
I just updated the plugin to 1.51

**Comment by GangaramD** [comment]
I have enabled the API in the locasettings.php

**Comment by GangaramD** [comment]
--- Git Changelog ---
---
ERROR: Step ‘Git Changelog’ aborted due to exception: 
java.lang.NoClassDefFoundError: Could not initialize class se.bjurr.gitchangelog.internal.settings.Settings
	at se.bjurr.gitchangelog.api.GitChangelogApi.<init>(GitChangelogApi.java:430)
	at se.bjurr.gitchangelog.api.GitChangelogApi.gitChangelogApiBuilder(GitChangelogApi.java:57)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:56)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.FilePath.act(FilePath.java:1083)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:40)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:52)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE

**Comment by tomasbjerre** [comment]
Do you build on slaves or just one master instance?

**Comment by GangaramD** [comment]
One master

**Comment by GangaramD** [comment]
Actually i am using xampp, i have setup the mediawiki at my localhost/modeiawiki and jenkins in xampp/tomcat/webapps/jenkins.

I am trying to create change file and publish it to the mediawiki.

**Comment by GangaramD** [comment]
Actually at first i was able to get generate the changelog.html file then i was triying to push the details to mediawiki there i got the internal.integration issue, then i updated the Localsetting.php with the API enale properties as you suggested and also i turn up with updating the plugin to 1.51. Now i am facing the above issue.

**Comment by tomasbjerre** [comment]
Ok. I tried to reproduce it in Docker but was unable to do so. Worked fine.

Perhaps that is a workaround for you? To use Docker instead. What I did exactly was:
* Clone https://github.com/tomasbjerre/jenkinsbitbucket
* docker-compose up
* Browse to http://localhost:8080/

**Comment by GangaramD** [comment]
K let me try.

**Comment by GangaramD** [comment]
I am lil new to docker but i trued as you instructed and facing the error,

  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
Failed to execute script docker-compose

**Comment by GangaramD** [comment]
Whats the configuration if I want to publish the changelog from one server(Linux) where the jenkins is installed to the other server(windows) on which the mediawiki is setup ?

**Comment by GangaramD** [comment]
I have tried this configuration but it fails to publish on mediawiki and i am facing below error,

![image](https://user-images.githubusercontent.com/22867715/29382829-8caee62c-82eb-11e7-92c0-d311cb722fe2.png)


--- Git Changelog ---
---
Posting changelog to http://10.35.5.234/mediawiki/index.php/DEVse.bjurr.gitchangelog.api.exceptions.GitChangelogIntegrationException: http://10.35.5.234/mediawiki DEV
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.createMediaWikiPage(MediaWikiClient.java:95)
	at se.bjurr.gitchangelog.api.GitChangelogApi.toMediaWiki(GitChangelogApi.java:134)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:167)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.FilePath.act(FilePath.java:1085)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:40)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:52)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:730)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Caused by: com.jayway.jsonpath.PathNotFoundException: Missing property in path $['login']
	at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:72)
	at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:77)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:151)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:502)
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.getWikiToken(MediaWikiClient.java:192)
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.doAuthenticate(MediaWikiClient.java:177)
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.createMediaWikiPage(MediaWikiClient.java:86)
	... 16 more

Finished: SUCCESS

**Comment by GangaramD** [comment]
I have update the API properties also.
$wgEnableAPI = true;
$wgEnableWriteAPI = true;

**Comment by GangaramD** [comment]
Can anyone help me out how can i resolve this issue, 

--- Git Changelog ---
---
Posting changelog to http://localhost/mediawiki//index.php/wikise.bjurr.gitchangelog.api.exceptions.GitChangelogIntegrationException: http://localhost/mediawiki/ wiki
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.createMediaWikiPage(MediaWikiClient.java:95)
	at se.bjurr.gitchangelog.api.GitChangelogApi.toMediaWiki(GitChangelogApi.java:134)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:167)
	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
	at hudson.FilePath.act(FilePath.java:1085)
	at org.jenkinsci.plugins.gitchangelog.perform.GitChangelogPerformer.performerPerform(GitChangelogPerformer.java:40)
	at org.jenkinsci.plugins.gitchangelog.GitChangelogRecorder.perform(GitChangelogRecorder.java:52)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
	at hudson.model.Run.execute(Run.java:1764)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)
Caused by: com.jayway.jsonpath.PathNotFoundException: Missing property in path $['login']
	at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:72)
	at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:77)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:147)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:502)
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.getWikiToken(MediaWikiClient.java:192)
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.doAuthenticate(MediaWikiClient.java:177)
	at se.bjurr.gitchangelog.internal.integrations.mediawiki.MediaWikiClient.createMediaWikiPage(MediaWikiClient.java:86)
	... 16 more

Finished: SUCCESS

**Comment by tomasbjerre** [comment]
Looks like it is broken (using deprecated API that is removed i later MediaWiki).

Anonymous edit seems to work if you can use that in your wiki. Just dont supply user/password and it might work.

**Comment by GangaramD** [comment]
Yes it worked without passing the username and password.

**Comment by GangaramD** [comment]
But what if I need to post the content change to mediawiki which is LDAP authenticated ?

**Comment by tomasbjerre** [comment]
Mediawiki changed how the authentication works... I'm asking someone for some help here: https://stackoverflow.com/questions/45779754/cannot-authenticate-with-mediawiki-1-28-api

**Comment by GangaramD** [comment]
Okay Thanks.!!! I will be monitoring the above thread too. Kindly let me know if u get any other solution for this.

**Comment by tomasbjerre** [comment]
I released 1.52 now with a possible fix. I'm not sure if it requires the user to be a bot-user but you may have to create a bot user to get it working.

**Comment by GangaramD** [comment]
How can I use this plugin twice in the Jenkins job ?  
Actually I need to create two changelog files, one with the particular tags details changes and the other file with all the commits details.

**Comment by tomasbjerre** [comment]
Should be no problem if you use a pipeline script.

**Comment by GangaramD** [comment]
You mean to say a downstream job ?

**Comment by tomasbjerre** [comment]
No, https://jenkins.io/doc/book/pipeline/

**Comment by GangaramD** [comment]
Thanks!!! Let me try this.

**Comment by GangaramD** [comment]
Is there any option (argument) to pass a particular tag value while using the Git changelog command line. I am able to create the changelog for all the git commits but I need for a specific tag.
 
This is what I have used for generating the changelog **./bin/git-changelog-command-line -t changelog.mustache -r . -tc GIT_COMMIT -tr ref/heads/master -of CHANGELOG.md**

**Is there any option to pass the tag number in the command line.**

I am trying to fetch the changelog of that particular build by passing build number which is same as the tag in the git changelog command line.

**Comment by tomasbjerre** [comment]
You can use the tag in `--to-ref` and `--from-ref`.

**Comment by GangaramD** [comment]
Thanks !!! it worked.
