### ISSUE TITLE
com.google.gson.Gson.newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader;

### ISSUE THREAD

**Issue by dmodoomsirius** [tomasbjerre/git-changelog-lib#56]
here is the debug.log with -d and -S enabled.

https://gist.github.com/dmodoomsirius/83db89e9ee38c4fde45d82d13e8458c3

**Comment by tomasbjerre** [comment]
And what is the problem?

**Comment by dmodoomsirius** [comment]
its failing to output the changelog.html this is the setup https://github.com/zmaster587/AdvancedRocketry/tree/gradleTest not sure why.

**Comment by tomasbjerre** [comment]
This is the interesting part:
```
Caused by: java.lang.NoSuchMethodError: com.google.gson.Gson.newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader;
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:35)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:116)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at se.bjurr.gitchangelog.internal.integrations.github.GitHubHelper.getIssueFromAll(GitHubHelper.java:36)
        at se.bjurr.gitchangelog.internal.issues.IssueParser.createParsedIssue(IssueParser.java:220)
        at se.bjurr.gitchangelog.internal.issues.IssueParser.parseForIssues(IssueParser.java:74)
        at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:438)
        at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:73)
        at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:97)
        at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:109)
        at se.bjurr.gitchangelog.api.GitChangelogApi.toFile(GitChangelogApi.java:121)
        at se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask.gitChangelogPluginTasks(GitChangelogTask.java:419)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

**Comment by tomasbjerre** [comment]
I created a PR with a workaround: https://github.com/zmaster587/AdvancedRocketry/pull/936

**Comment by dmodoomsirius** [comment]
that PR fixed the issue thank you very much for the help!
