### ISSUE TITLE
se.bjurr.gitchangelog.api.exceptions.GitChangelogRepositoryException:

### ISSUE THREAD

**Issue by cantswim24** [tomasbjerre/git-changelog-lib#64]
trying to generate a changelog and I get the exception below...

My release note generator has worked before and has suddenly started doing this?

any ideas?

14:11:35 ---
14:11:35 --- Git Changelog ---
14:11:35 ---
14:11:35 se.bjurr.gitchangelog.api.exceptions.GitChangelogRepositoryException: 
14:11:35 	at se.bjurr.gitchangelog.internal.git.GitRepo.getCommit(GitRepo.java:101)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.getId(GitChangelogApi.java:480)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:429)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:77)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:99)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:123)
14:11:35 	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:151)
14:11:35 	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
14:11:35 	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
14:11:35 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
14:11:35 	at hudson.remoting.Request$2.run(Request.java:364)
14:11:35 	at 

everything was as before

**Comment by tomasbjerre** [comment]
What version?

**Comment by tomasbjerre** [comment]
The interesting part of the stacktrace is left out in your description. There is more information further down.

**Comment by cantswim24** [comment]
getting you veersion shortly but here is the full trace...

14:11:35 se.bjurr.gitchangelog.api.exceptions.GitChangelogRepositoryException: 
14:11:35 	at se.bjurr.gitchangelog.internal.git.GitRepo.getCommit(GitRepo.java:101)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.getId(GitChangelogApi.java:480)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:429)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.getChangelog(GitChangelogApi.java:77)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:99)
14:11:35 	at se.bjurr.gitchangelog.api.GitChangelogApi.render(GitChangelogApi.java:123)
14:11:35 	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:151)
14:11:35 	at org.jenkinsci.plugins.gitchangelog.perform.RemoteCallable.call(RemoteCallable.java:29)
14:11:35 	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
14:11:35 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
14:11:35 	at hudson.remoting.Request$2.run(Request.java:364)
14:11:35 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
14:11:35 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:11:35 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:11:35 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:11:35 	at java.lang.Thread.run(Thread.java:748)
14:11:35 Caused by: org.eclipse.jgit.errors.RevisionSyntaxException: a69197eb
14:11:35 	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:755)
14:11:35 	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:435)
14:11:35 	at se.bjurr.gitchangelog.internal.git.GitRepo.getCommit(GitRepo.java:99)
14:11:35 	... 15 more
14:11:35 
14:11:35 ERROR: Build step failed with exception

**Comment by tomasbjerre** [comment]
There should be more stack trace in the jenkins system log.

But so far it looks like a reference or commit hash cannot be found. Perhaps you have started doing shallow clones or a tag or branch is not fetched.

**Comment by cantswim24** [comment]
Thanks Tomas I will retry
